### ISSUE TITLE
Not an issue, so much as some questions

### ISSUE THREAD

**Issue by labaxter** [gmpassos/reflection_factory#3]
I saw your reference to reflection_factory in a thread about the dart:mirror module.
 I have two questions:

1. can reflection_factory be used as a replacement for json_serializable?
2. if yes, will "dart compile exe" fail if I use your reflection_factory the way it does when using json_serializable?
3. if no, (I doubt this) could importing reflection_factory, cause json_serializable to no longer cause this compilation issue?

You can see my use case in a comment below yours.

Thanks

**Comment by gmpassos** [comment]
I use 'reflection_factory' with a project that is compiled with 'dart compile exe' and also another that compiles to JS/Web.
